### ISSUE TITLE
Jonathan Yeong: To bundle or not to bundle - diving into the JS module/no-module bundler ecosystem

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#10]
# Tasks:

- [ ] Collect content: 
  - [ ] Get slides
  - [ ] Get bio
  - [ ] Get contact links
  - [ ] Get headshot
- [ ] Pair with mentor
- [ ] Schedule
- [ ] Add to channel
- [ ] Sound/AV check
- [ ] Check-in week before
- [ ] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:
## Jonathan Yeong: To bundle or not to bundle - diving into the JS module/no-module bundler ecosystem

> There are so many tools out there, I found it a little overwhelming. I wanted to discuss the features of both module and no module bundlers. And talk about cases where we would want to use one over the other. The takeaway of the talk would be an understanding of what tool to use for your next JS project.

Length: 10 minutes
Would like mentoring: Yes

Additional thoughts:
> Thanks for giving us the opportunity to give talks! I actually have no idea how much time I'll need, but I think 10 minutes is enough to go deep without being overwhelming.
