### ISSUE TITLE
Kirk Shillingford: Fuzz-Testing in Typescript

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#11]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [x] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

## Kirk Shillingford: 

> 

Length: 15 minutes
Would like mentoring: no
