### ISSUE TITLE
Marie Antons: Linked List Data Structures

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#12]
# Tasks:

- [ ] Collect content: 
  - [ ] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [ ] Get headshot
- [x] Pair with mentor
- [ ] Schedule
- [ ] Add to channel
- [ ] Sound/AV check
- [ ] Check-in week before
- [ ] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

## Marie Antons: Linked List Data Structures

> I will go over the basic structure of Linked lists and tell people more about them. Maybe give some code snippets and talk about test cases.

Length: 15 minutes
Would like mentoring: Yes
