### ISSUE TITLE
Barbara Law: Coding Challenges - not just for whiteboarding

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#13]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [ ] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:
## Barbara Law: Coding Challenges - not just for whiteboarding

> I'm a beginner and want to share how particpaiin coding challenges like Advent of Code, Scrimba weekly challenges, and codewars have increased my confidence, opened up communities and conversations for me, and brought focus to my study.

Length: 5 minutes
Would like mentoring: Yes

Additional thoughts:
> I'm mostly nervous about the technical aspects of presenting - sharing the slides, etc.
