### ISSUE TITLE
Courtney Landau: Breaking down coding problems in interviews

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#14]
# Tasks:

- [ ] Collect content: 
  - [ ] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [ ] Get headshot
- [ ] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before
- [ ] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

## Courtney Landau: Breaking down coding problems in interviews

> I will talk about how I break down problems in coding interviews into a series of steps.

Length: 10 minutes
Would like mentoring: No

Additional thoughts:
> It took me so long to submit this because I was trying to come up with an interesting name. and I failed :)
