### ISSUE TITLE
Glen McCallum: Transitioning from IC to Management

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#15]
# Tasks:

- [ ] Collect content: 
  - [ ] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [ ] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

## Glen McCallum: Transitioning from IC to Management

> Over the past 2 years I've moved from a senior development role to an engineering management role. This talk would be a raw peek into my experience. Some of the painful moments - tears definitely. Some of the gotchas. And maybe a few victories (time permitting).

Length: 10 minutes
Would like mentoring: No
