### ISSUE TITLE
Vic Vijayakumar: Building minimum viable products with low-code tools

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#16]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [ ] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [ ] Sound/AV check
- [x] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

## Vic Vijayakumar: Building minimum viable products with low-code tools

> This will be a short talk about setting up a NextJS site that is backed by an Airtable database.

Length: 10 minutes
Would like mentoring: No
