### ISSUE TITLE
Nerando Johnson: ReadMes .... yup,  they are magical

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#17]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [ ] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

## Nerando Johnson: ReadMes .... yup,  they are magical .

> Highlighting the importance of readmes as a dev and how to craft them.

Length: 20 minutes
Would like mentoring: no answer
