### ISSUE TITLE
Chris DeMars: A11Y

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/VC-Community-Docs#18]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [x] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [ ] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:
