### ISSUE TITLE
Rafi - IPFS - Interplanetary file system

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#26]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [x] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

## Rafi - IPFS - Interplanetary file system
rafi@hey.com
> IPFS is new alternative to http which allows you to build decentralized web. In this talk we will look at what IPFS is how to host your website in IPFS and how to access IPFS websites
- 20 minutes
- Would like mentoring: Yes
