### ISSUE TITLE
Mark Rafi as paired with mentor Kyle Conway 

### ISSUE THREAD

**Issue by srgupta** [Virtual-Coffee/VC-Community-Docs#39]
# Tasks:

- [ ] Collect content: 
  - [ ] Get slides
  - [ ] Get bio
  - [ ] Get contact links
  - [ ] Get headshot
- [ ] Pair with mentor
- [ ] Schedule
- [ ] Add to channel
- [ ] Sound/AV check
- [ ] Check-in week before -  get final length of time for talk, and final talk description
- [ ] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

# Notes
## {Speaker Name} - {time scheduled}
{Twitter Handle} 
- Topic Title: {add title}

- Bio: {bio}
- Talk Description:  {Add description}
- Slides Link: {Add slides link}
