### ISSUE TITLE
Todd Libby: Accessibility

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/VC-Community-Docs#44]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [ ] Schedule
- [ ] Add to channel
- [x] Sound/AV check
- [ ] Check-in week before -  get final length of time for talk, and final talk description
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:
- didn't submit form, but talking about accessibility

# Notes
## {Speaker Name} - {time scheduled}
{Twitter Handle} 
- Topic Title: {add title}

- Bio: {bio}
- Talk Description:  {Add description}
- Slides Link: {Add slides link}
