### ISSUE TITLE
Dan Ott: Graceful Solutions to Tricky Layouts with CSS Grid

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#46]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [x] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before -  get final length of time for talk, and final talk description
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

```
Your Name:
Dan Ott
Email
dan@virtualcoffee.io
What is the working title for your talk?
CSS Grid is dope
Tell us more about your topic.
CSS Grid is dope. I'm thinking I'll show a few different ways to use CSS Grid to solve common problems in cool ways.
How long do you think your talk will be?
10 minutes
Would Like Mentorship
No
Do you have any additional thoughts about the Lightning Talks?
(⌐■_■)
```

# Notes
## {Speaker Name} - {time scheduled}
{Twitter Handle} 
- Topic Title: {add title}

- Bio: {bio}
- Talk Description:  {Add description}
- Slides Link: {Add slides link}
