### ISSUE TITLE
Bekah Hawrot Weigel: You have what they don't: Leveraging your non-traditional background

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/VC-Community-Docs#49]
# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [x] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [ ] Check-in week before -  get final length of time for talk, and final talk description
- [ ] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:
Talking about taking non-tradition experiences, work-related or otherwise, and using that to gain confidence in learning to code and applying for jobs.
# Notes
## Bekah Hawrot Weigel - {time scheduled}
@BekahHW  
- Topic Title: You have what they don't: Leveraging your non-traditional background

- Bio: Bekah graduated from the Flatiron School Software Engineering program in May of 2019 and since then she has started a consultancy specializing in front-end development, created a developer community called Virtual Coffee, stayed active on Twitter and in tech-related slack groups, spoke on podcasts and at conferences, and has continued to mom her four kids. Prior to tech, she spent 10 years teaching college English, three years organizing events and community, and fully embraces being a writer of many genres: code, non-fiction, screenplay, poetry, curriculum. 

Twitter: https://twitter.com/BekahHW
Website: https://bekahhw.github.io
Virtual Coffee: https://virtualcoffee.io
- Talk Description: We all bring something to the table, a different perspective, a different experience, an opportunity to allow other people to grow by sharing our own perspectives, a skillset. And when we share our own experiences, when we leverage our backgrounds, not only do we offer others an opportunity to grow by understanding our perspective, but we also invite them to share their own perspectives so we can grow. And the depth created by approaching a problem from multiple perspectives is the growth and development we all should strive for.
Talking about taking non-tradition experiences, work-related or otherwise, and using that to gain confidence in learning to code and applying for jobs
- Slides Link: {Add slides link}
https://docs.google.com/presentation/d/1APdg8PRbMOek5mNto5vO6tEZVxaxc2tmNh77UfUnhYs/edit#slide=id.gaf319132fd_0_9

https://drive.google.com/file/d/1cSOjaa05dRXIpGIFia38eT_8USF5ePnK/view?usp=sharing
