### ISSUE TITLE
MARCH CHALLENGE: Get job Ready!

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/VC-Community-Docs#56]
# March Monthly Challenge

## How It Works
{Explanation}

## To-Dos
- [ ] Fill in content
- [ ] Get up on site
- [ ] deteremine tracking needs
- [ ] add to slack channel
- [ ] change slack channel topic
- [ ] Do weekly check-ins
