### ISSUE TITLE
MONTHLY-CHALLENGE: May 2021, Accessibility

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/VC-Community-Docs#57]
# May Monthly Challenge

## How It Works
{Explanation}

## To-Dos
- [ ] Fill in content
- [ ] Get up on site
- [ ] deteremine tracking needs
- [ ] add to slack channel
- [ ] change slack channel topic
- [ ] Do weekly check-ins
