### ISSUE TITLE
Mike Rogers: Dockerizing Application

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/VC-Community-Docs#9]
Mike Rogers: Dockerizing Application
10 Minutes

# Tasks:

- [x] Collect content: 
  - [x] Get slides
  - [x] Get bio
  - [x] Get contact links
  - [x] Get headshot
- [x] Pair with mentor
- [x] Schedule
- [x] Add to channel
- [x] Sound/AV check
- [x] Check-in week before
- [x] Check-in the day of
- [ ] Create intro slide (template in #5)

# Info from form:

Mike Rogers
me@mikerogers.io
Dockerizing Application
Docker allowed me to extract lots of my apps complexity by reducing the amount of dependencies I had to install.  I want to share information about how to get up & going, with enough working knowledge to have fun :D
10 minutes
I'm super excited! I will want to confirm I can do it in February (I might have a clash, but I'm not 100%).
